name: testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - test
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - name:  test1
        run: echo "check-one"
  two:
    runs-on: ubuntu-latest
    needs: first
    steps:
      - name: tst2
        run: echo "check-two"
  three:
    runs-on: ubuntu-latest
    needs: two
    steps:
      - name: test3
        run: echo "check-three"
