name: pod

on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: use contaext variable
        run:  |
          echo "this workflowis triggered by ${{ github.actor }}
          echo "this repository name is ${{ github.repository }}


