name: testing-pod/context variables

on: push
jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: use contaext variable
        run:  |
          echo "this workflowis triggered by ${{ GitHub.actor }}
          echo "this repository name is ${{ GitHub.repository }}


